configured_endpoints: 19
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/irrigation-solutions-software-development/seshtahvcode-py-cli-1eaaafdc4b813c5f27ec0efef2734bf26251dd723779f2156a6ecbb44b612476.yml
openapi_spec_hash: 356a7298b2abac3fdf72ad5ee046b952
config_hash: 23a9924e640bbb26d7b9cd430fb305f7
