configured_endpoints: 19
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/irrigation-solutions-software-development/seshtahvcode-py-cli-06eca8c5fac2bdfdfdd0ac4e7e8563ecc18802c3e98546e40c6e9e2bbb6ea382.yml
openapi_spec_hash: 356a7298b2abac3fdf72ad5ee046b952
config_hash: c6a666c6a3b2f4e9340bcbd1aad28f64
